//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NativeHello {

public class NativeHello {
  public static string getPlatformABI() {
    string ret = NativeHelloPINVOKE.getPlatformABI();
    return ret;
  }

}

}
